server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5 # 拉取服务的间隔时间

zuul:
  prefix: /api # 路由路径前缀
  routes:
    item-service: /item/** # 商品微服务的映射路径
    search-service: /search/** # 搜索微服务
    user-service: /user/** # 用户微服务
    auth-service: /auth/** # 授权中心微服务
    cart-service: /cart/** #购物车微服务
    order-service: /order/** #订单微服务
  add-host-header: true
  sensitive-headers:  # 什么都不写设位空，覆盖默认敏感头信息
leyou:
  jwt:
    pubKeyPath: E:\\Other\\leyou\\rsa\\rsa.pub # 生成公钥的地址
    cookieName: LY_TOKEN
  filter:
    allowPaths: # 过滤白名单
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item
